Frontend unit test fix (#1169)
* Fixed unit tests

- fixed import path
- added missing provider
- null check

* Fixed frontend test etc.

- added missing imports for test
- added null check for site and organization since corresponding service could return null
- use String instead of string in string-utils, which caused error in unit test

* Increased timeouts and retry in karma.conf.js to tolerate slower machine

* Added missing imports for frontend unit tests

* null check

* Added missing imports and provides for frontend unit tests

* Added missing provides for frontend unit tests

* Fixed ConfigCodePipe test

* Refactored all onlyBc directive to inBc due to angular restriction on naming

- unit tests were failing:
Error: Binding to event property 'onlyBc' is disallowed for security reasons, please use (lyBc)=...

* Implemented mock functions for mock-access-token-service

- to satisfy unit tests

* Added missing import

* mocked BrokerProfile obj

* Added missing provide for RolePipe test

* Added missing  required provides for test

* Fixed routes in test

* Use mock to satisfy unit test instead of doing null check on component