Refactored all onlyBc directive to inBc due to angular restriction on naming
- unit tests were failing:
Error: Binding to event property 'onlyBc' is disallowed for security reasons, please use (lyBc)=...